import os
import sys
import setuptools
import pathlib

install_requires = ["pyusb"]
tests_require = ["pytest", "pytest-cov", "pytest-flake8"]
dev_requires = install_requires + tests_require + ["documenteer[pipelines]"]
scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="pypcv",
    description="Python Power Commander V.",
    use_scm_version={
        "write_to": "pypcv/version.py",
        "write_to_template": scm_version_template,
    },
    setup_requires=["setuptools_scm", "pytest-runner"],
    install_requires=install_requires,
    package_dir={"": "pypcv"},
    packages=setuptools.find_namespace_packages(where="pypcv"),
    scripts=[],
    tests_require=tests_require,
    extras_require={"dev": dev_requires},
    license="GPLv3",
    project_urls={"Source Code": "https://github.com/tribeiro/pypcv"},
)
